apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2019-03-01T16:15:11Z
  generation: 1
  name: mivb-9-1-0-14
  namespace: default
  resourceVersion: "3657"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/mivb-9-1-0-14
  uid: 30940f4d-3c3d-11e9-9ffa-42010a800047
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: my-mivb-9-1-0-14
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: my-mivb-9-1-0-14
    spec:
      containers:
      - image: us.gcr.io/symphony-231521/mivb:9.1.0.14-01
        imagePullPolicy: IfNotPresent
        name: tenant
        ports:
        - containerPort: 443
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - ALL
          privileged: true
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /home/e-smith/db-pv
          name: mivb-persistent-storage
          subPath: home/e-smith/db-pv
        - mountPath: /usr/libexec/mitel-3300icp/db-pv
          name: mivb-persistent-storage
          subPath: usr/libexec/mitel-3300icp/db-pv
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: mivb-persistent-storage
        persistentVolumeClaim:
          claimName: mivb-volumeclaim
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2019-03-01T16:17:11Z
    lastUpdateTime: 2019-03-01T16:17:11Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-03-01T16:15:11Z
    lastUpdateTime: 2019-03-01T16:17:11Z
    message: ReplicaSet "mivb-9-1-0-14-6cc59c45f4" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
