apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: 2019-03-01T16:14:33Z
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: us-central1
    failure-domain.beta.kubernetes.io/zone: us-central1-a
  name: mivb-sibel-pv
  resourceVersion: "3320"
  selfLink: /api/v1/persistentvolumes/mivb-sibel-pv
  uid: 1a01cb21-3c3d-11e9-9ffa-42010a800047
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mivb-volumeclaim
    namespace: default
    resourceVersion: "3318"
    uid: 215bacfa-3c3d-11e9-9ffa-42010a800047
  gcePersistentDisk:
    fsType: ext4
    pdName: mivb-sibel-disk
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
status:
  phase: Bound
