apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-01T19:39:54Z
  name: micollab
  namespace: default
  resourceVersion: "30619"
  selfLink: /api/v1/namespaces/default/services/micollab
  uid: c97b76fd-3c59-11e9-9ffa-42010a800047
spec:
  clusterIP: 10.27.251.251
  ports:
  - name: 22-to-22-tcp
    port: 22
    protocol: TCP
    targetPort: 22
  - name: 7050-to-7050-tcp
    port: 7050
    protocol: TCP
    targetPort: 7050
  selector:
    run: my-micollab
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
