apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2019-03-04T16:51:10Z
  name: mivb
  namespace: default
  resourceVersion: "581908"
  selfLink: /api/v1/namespaces/default/services/mivb
  uid: b6a719e1-3e9d-11e9-8d61-42010a8000fb
spec:
  clusterIP: 10.27.250.250
  ports:
  - name: 6800-to-6800-tcp
    port: 6800
    protocol: TCP
    targetPort: 6800
  - name: 6801-to-6801-tcp
    port: 6801
    protocol: TCP
    targetPort: 6801
  - name: 6802-to-6802-tcp
    port: 6802
    protocol: TCP
    targetPort: 6802
  - name: 3999-to-3999-tcp
    port: 3999
    protocol: TCP
    targetPort: 3999
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  - name: 5320-to-5320-tcp
    port: 5320
    protocol: TCP
    targetPort: 5320
  - name: 5060-to-5060-tcp
    port: 5060
    protocol: TCP
    targetPort: 5060
  - name: 5061-to-5061-tcp
    port: 5061
    protocol: TCP
    targetPort: 5061
  - name: 5060-to-5060-udp
    port: 5060
    protocol: UDP
    targetPort: 5060
  - name: 5061-to-5061-udp
    port: 5061
    protocol: UDP
    targetPort: 5061
  - name: 7050-to-7050-tcp
    port: 7050
    protocol: TCP
    targetPort: 7050
  - name: 20001-to-20001-udp
    port: 20001
    protocol: UDP
    targetPort: 20001
  selector:
    run: my-mivb-9-1-0-14
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
